---

title: "finalBoxplots"
author: "Nazanin Zounemat Kermani"
date: "January 27, 2018"
output: html_document
---
#Read the data and interpolate
```{r}

pathTodata = "C:/Users/nz1413/Desktop/"
PathToReport = "C:/Users/nz1413/Desktop/AnalysisTag/DiseaseSubTypeDiscovery/Final/report/"
  
# 1- read gene expression data
data <- t(read.table(paste(pathTodata, "/dataTAC/sputum_508genes.txt", sep = ""),  header = TRUE))
# 2- scale gene expression data(zere mean, one variance)
dataScaled = scale(data)

# 3- read Kuo labels
TAClabels <- t(read.table(paste(pathTodata,"dataTAC/correspondanceTAC.txt",sep=""),  header = FALSE))

clinical <- read.table(paste(pathTodata, "dataTAC/clinical_620Modified.csv", sep=""),  header = TRUE, sep = ",")

inds = match(TAClabels[2,], rownames(data))
tacLabels <- as.numeric(TAClabels[1,])
dataScaled = dataScaled[inds,]

library(mclust)
mbc<-Mclust(dataScaled)
summary(mbc)
temp  = factor(mbc$classification)
levels(temp)=c("TAC1", "TAC3a", "TAC2", "TAC3b")
mbc$classification = temp

# find the clinical vatiable for data
temp = match(rownames(dataScaled) , as.character(clinical$Patient))
clinicalData = clinical[temp,]
# Data imputation
clinicalData$gp = mbc$classification
indout = rep(1,dim(clinicalData)[2])
for(i in 4:dim(clinicalData)[2])
{
  if(is.numeric(clinicalData[,i]))
  {
    if(length(which(is.na(clinicalData[,i])))/length(clinicalData$gp) < 0.2)
      indout[i]=0
    
  }
}

forPlot = clinicalData[,which(indout==0)]
library(missForest)
forplot.imp = missForest(forPlot, maxiter = 100, ntree = 10000, verbose = TRUE )
imputatedClinicalData = forplot.imp$ximp
require(reshape2)


Label = mbc$classification
imputatedClinicalData$Label = factor(Label) 


```
##  TAC1:4
```{r}



# pdf('C:/Users/nz1413/Desktop/AnalysisTag/Final/data/TAC123abClinicalVariablesBoxPlot.pdf')
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot1.png',sep=''))
require(ggplot2)
i=1
for(i in 1:dim(imputatedClinicalData)[2])

  {
  png(paste(PathToReport, 'boxplots/TAC123ab ', colnames(imputatedClinicalData)[i],  '.png' ,sep=''))
  
  df.m <- melt(imputatedClinicalData[,c(i,27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
}
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot2.png',sep=''))

  i=4
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p
  dev.off()
  i=7
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot3.png',sep=''))
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
  
  png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot4.png',sep=''))
  

    i=10
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot5.png',sep=''))
    i=13
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot6.png',sep=''))
    i=16
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot7.png',sep=''))
    i=19
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
    i=22
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot8.png',sep=''))
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC123abClinicalVariablesBoxPlot9.png',sep=''))
    i=25
  df.m <- melt(imputatedClinicalData[,c(i:(i+1),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()

```

##  Tac12 against Tac3a,b


```{r}
TAC12And3Label = Label
levels(TAC12And3Label) = c("TAC12", "TAC3ab","TAC12","TAC3ab")
imputatedClinicalData$Label = TAC12And3Label 
i=1
for(i in 1:dim(imputatedClinicalData)[2])

  {
 png(paste(PathToReport, 'boxplots/TAC12AGAINT3ab ', colnames(imputatedClinicalData)[i],  '.png' ,sep=''))
  
  df.m <- melt(imputatedClinicalData[,c(i,27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
}

# pdf('C:/Users/nz1413/Desktop/AnalysisTag/Final/data/TAC12Against3ClinicalVariablesBoxPlot2.pdf')
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot1.png',sep=''))
require(ggplot2)
i=1
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot2.png',sep=''))
  i=4
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot2.png',sep=''))
  i=7
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot3.png',sep=''))
    i=10
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
    dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot4.png',sep=''))
    i=13
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
    dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot1.png',sep=''))
    i=16
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
    dev.off()
    png(paste(PathToReport, 'boxplots/TAC12Against3ClinicalVariablesBoxPlot8.png',sep=''))
    i=19
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
    dev.off()

    png(paste(PathToReport, 'boxplots/TAC12Against3ClinicalVariablesBoxPlot9.png',sep=''))
      i=22
  df.m <- melt(imputatedClinicalData[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
    dev.off()

    png(paste(PathToReport, 'boxplots/TAC12Against3ClinicalVariablesBoxPlot10.png',sep=''))
      i=25
  df.m <- melt(imputatedClinicalData[,c(i:(i+1),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
```

Tac3a and Tac3b
```{r}



ind34 = c(which(Label == "TAC3a"), which(Label == "TAC3b"))
imputatedClinicalData3ab = imputatedClinicalData[ind34,]
imputatedClinicalData3ab$Label = droplevels(as.factor(Label[ind34]))
for(i in 1:dim(imputatedClinicalData)[2])

  {
 png(paste(PathToReport, 'boxplots/TAC3aAGAINT3b ', colnames(imputatedClinicalData)[i],  '.png' ,sep=''))
  
  df.m <- melt(imputatedClinicalData3ab[,c(i,27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
}
# 
# pdf('C:/Users/nz1413/Desktop/AnalysisTag/Final/data/TAC3aTACbClinicalVariablesBoxPlot2.pdf')
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot0.png',sep=''))
require(ggplot2)
i=1
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot2.png',sep=''))
  i=4
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot3.png',sep=''))
  i=7
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot4.png',sep=''))
    i=10
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot5.png',sep=''))
    i=13
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot6.png',sep=''))
    i=16
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot7.png',sep=''))
    i=19
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot8.png',sep=''))
    i=22
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+3),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
  dev.off()
png(paste(PathToReport, 'boxplots/TAC3abClinicalVariablesBoxPlot9.png',sep=''))
    i=25
  df.m <- melt(imputatedClinicalData3ab[,c(i:(i+1),27)], id.var = "Label")
  p <- ggplot(data = df.m, aes(x=variable, y=value)) 
  p <- p + geom_boxplot(aes(fill=Label))
  p <- p + geom_jitter()
  p <- p + facet_wrap( ~ variable, scales="free")
  # p <- p + xlab("x-axis") + ylab("y-axis") + ggtitle("Title")
  p <- p + guides(fill=guide_legend(title="Legend_Title"))
  p 
dev.off()
```